format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $golang\
  $rust\
  $java\
  $python\
  $nodejs\
  $terraform\
  $kubernetes\
  $helm\
  $aws\
  $cmd_duration\
  $custom\
  $status\
  $line_break\
  $jobs\
  $battery\
  $time\
  $character\
  """

#------------------------------------------------------------------------------
# System (host, user, directory, version control)
#------------------------------------------------------------------------------

[git_branch]
disabled = false
format = ' [ÓÇ† $branch](bold purple)'
truncation_length = 10
truncation_symbol = "‚Ä¶"
only_attached = false

[git_commit]
disabled = false
format = ' [$hash $tag](bold green)'
only_attached = false

[git_status]
disabled = false
format = ' [$all_status$ahead_behind](bold red)'
stashed = "üì¶"
modified = "~"

#------------------------------------------------------------------------------
# Programming Languages
#------------------------------------------------------------------------------

[golang]
disabled = true
format = ' [üêπ $version](bold cyan)'

[rust]
disabled = false
format = ' [ü¶Ä $version](bold red)'

[python]
disabled = false
format = ' [üêç ${pyenv_prefix}(${version})$virtualenv](bold yellow)'

[java]
disabled = false
format = ' [‚òï $version](bold brown)'

[nodejs]
disabled = false
format = ' [‚¨¢ $version](bold green)'

#------------------------------------------------------------------------------
# Cloud
#------------------------------------------------------------------------------

[terraform]
disabled = false
format = ' [‚ñ∞ $version$workspace](bold 105)'

[kubernetes]
disabled = false
format = ' [‚ò∏ $context:$namespace](bold blue)'
[kubernetes.context_aliases]
"arn:aws:eks:us-west-2:643342778636:cluster/dev-eks-usw2-hawking-3" = "dev-eks-usw2-hawking-3"

[helm]
disabled = false
format = ' [‚ò∏ $version](bold white)'

[aws]
disabled = true
format = ' [‚òÅÔ∏è $profile:$region](bold yellow)'
[aws.region_aliases]
us-east-1 = "use1"
us-west-2 = "usw2"
eu-central-1 = "euc1"

[gcloud]
disabled = true

#------------------------------------------------------------------------------
# Shell (command execution status, duration)
#------------------------------------------------------------------------------

[status]
disabled = false
symbol = "‚ö†Ô∏è"
format = ' [$symbol $common_meaning$signal_name$maybe_int]($style)'

[character]
success_symbol = "[‚ô™]()"
error_symbol = "[√∏](red)"
vicmd_symbol = "[V](blue)"

[cmd_duration]
disabled = false
format = ' [$duration](bold yellow)'
