format = '$username$hostname$directory$shell$shlvl$git_branch$git_commit$git_state$git_status$golang$rust$java$python$nodejs$terraform$kubernetes$helm$aws$cmd_duration$custom$status$jobs$battery$time$line_break$character'

[username]
disabled = true
format = '[$user]($style)@'
show_always = false

[hostname]
disabled = true
format = '[$hostname]($style):'
ssh_only = false

[directory]
disabled = false
format = '[$path]($style)[$read_only]($read_only_style)'

[shell]
disabled = false
format = ' [$indicator]($style)'
zsh_indicator = ''
bash_indicator = 'bash'
fish_indicator = 'fish'
powershell_indicator = 'posh'
ion_indicator = 'ion'
elvish_indicator = 'elvish'
tcsh_indicator = 'tcsh'
xonsh_indicator = 'xonsh'
unknown_indicator = 'unknown shell'

[shlvl]
disabled = false
format = ' [$shlvl]($style)'

[git_branch]
disabled = false
format = ' [ÓÇ† $branch](bold purple)'
truncation_length = 10
truncation_symbol = '‚Ä¶'
only_attached = false

[git_commit]
disabled = false
format = ' [$hash $tag](bold green)'

[git_status]
disabled = true
format = ' [$all_status$ahead_behind](bold red)'
stashed = 'üì¶'
modified = '~'

[golang]
disabled = true
format = ' [üêπ $version](bold cyan)'

[rust]
disabled = false
format = ' [ü¶Ä $version](bold red)'

[python]
disabled = false
format = ' [üêç ${pyenv_prefix}(${version})$virtualenv](bold yellow)'

[java]
disabled = false
format = ' [‚òï $version](bold brown)'

[nodejs]
disabled = false
format = ' [‚¨¢ $version](bold green)'

[terraform]
disabled = true
format = ' [‚ñ∞ $version$workspace](bold 105)'

[kubernetes]
disabled = true
format = ' [‚ò∏ $context:$namespace](bold blue)'

[helm]
disabled = false
format = ' [‚ò∏ $version](bold white)'

[aws]
disabled = true
format = ' [‚òÅÔ∏è $profile:$region](bold yellow)'

[aws.region_aliases]
us-east-1 = 'use1'
us-west-2 = 'usw2'
eu-central-1 = 'euc1'

[gcloud]
disabled = true

[status]
disabled = false
symbol = '‚ö†Ô∏è'
format = ' [$symbol $common_meaning$signal_name$maybe_int]($style)'

[character]
success_symbol = '[‚ô™]()'
error_symbol = '[√∏](red)'
vicmd_symbol = '[V](blue)'

[cmd_duration]
disabled = false
format = ' [$duration](bold yellow)'
